name: pre-commit

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10"
  SKIP: cargo-fmt,cargo-clippy,cargo-check,cargo-test,cargo-test-doc,cargo-doc

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      ## Run pre-commit
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
